# Generated by Django 4.1.13 on 2024-10-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BloomHub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_id", models.CharField(max_length=50, unique=True)),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "youtube_api_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "wikifier_api_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "profileImg",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.DeleteModel(name="User",),
    ]
