# Generated by Django 4.1.13 on 2024-11-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BloomHub", "0002_bloomuser_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloomuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bloomuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
