# Generated by Django 4.1.13 on 2024-11-02 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BloomHub", "0004_bloomuser_groups_bloomuser_user_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("vid", models.URLField()),
                ("setTime", models.IntegerField()),
                ("uploader", models.CharField(max_length=255)),
                ("view_count", models.IntegerField()),
                (
                    "std_lang",
                    models.CharField(
                        choices=[("KR", "Korean"), ("EN", "English")], max_length=2
                    ),
                ),
                ("learning_status", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
