# Generated by Django 4.1.13 on 2024-11-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "BloomHub",
            "0005_bloomdictionary_learningvideo_worddata_sentencedata_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloomdictionary",
            name="language",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="bloomdictionary", unique_together={("language", "stage")},
        ),
    ]
